const Items = [
  { co_ibge: 12, sg_uf: 'AC', no_uf: 'Acre' },
  { co_ibge: 27, sg_uf: 'AL', no_uf: 'Alagoas' },
  { co_ibge: 13, sg_uf: 'AM', no_uf: 'Amazonas' },
  { co_ibge: 16, sg_uf: 'AP', no_uf: 'Amapá' },
  { co_ibge: 29, sg_uf: 'BA', no_uf: 'Bahia' },
  { co_ibge: 23, sg_uf: 'CE', no_uf: 'Ceará' },
  { co_ibge: 53, sg_uf: 'DF', no_uf: 'Distrito Federal' },
  { co_ibge: 32, sg_uf: 'ES', no_uf: 'Espírito Santo' },
  { co_ibge: 52, sg_uf: 'GO', no_uf: 'Goiás' },
  { co_ibge: 21, sg_uf: 'MA', no_uf: 'Maranhão' },
  { co_ibge: 51, sg_uf: 'MT', no_uf: 'Mato Grosso' },
  { co_ibge: 50, sg_uf: 'MS', no_uf: 'Mato Grosso do Sul' },
  { co_ibge: 31, sg_uf: 'MG', no_uf: 'Minas Gerais' },
  { co_ibge: 15, sg_uf: 'PA', no_uf: 'Pará' },
  { co_ibge: 25, sg_uf: 'PB', no_uf: 'Paraíba' },
  { co_ibge: 41, sg_uf: 'PR', no_uf: 'Paraná' },
  { co_ibge: 26, sg_uf: 'PE', no_uf: 'Pernambuco' },
  { co_ibge: 22, sg_uf: 'PI', no_uf: 'Piauí' },
  { co_ibge: 33, sg_uf: 'RJ', no_uf: 'Rio de Janeiro' },
  { co_ibge: 24, sg_uf: 'RN', no_uf: 'Rio Grande do Norte' },
  { co_ibge: 43, sg_uf: 'RS', no_uf: 'Rio Grande do Sul' },
  { co_ibge: 11, sg_uf: 'RO', no_uf: 'Rondônia' },
  { co_ibge: 14, sg_uf: 'RR', no_uf: 'Roraima' },
  { co_ibge: 28, sg_uf: 'SE', no_uf: 'Sergipe' },
  { co_ibge: 35, sg_uf: 'SP', no_uf: 'São Paulo' },
  { co_ibge: 42, sg_uf: 'SC', no_uf: 'Santa Catarina' },
  { co_ibge: 17, sg_uf: 'TO', no_uf: 'Tocantins' },
];

export default Items;
