export const FETCH_ALL_ADESOES_MUNICIPIO = 'FETCH_ALL_ADESOES_MUNICIPIO';
export const EMPTY_ADESOES_MUNICIPIO = 'EMPTY_ADESOES_MUNICIPIO';
export const FILTER_ADESOES_MUNICIPIO = 'FILTER_ADESOES_MUNICIPIO';
export const RESET_FILTER_ADESOES_MUNICIPIO = 'RESET_FILTER_ADESOES_MUNICIPIO';

export const FETCH_ALL_REPRESENTANTES_MUNICIPIO = 'FETCH_ALL_REPRESENTANTES_MUNICIPIO';
export const EMPTY_REPRESENTANTES_MUNICIPIO = 'EMPTY_REPRESENTANTES_MUNICIPIO';
export const FILTER_REPRESENTANTES_MUNICIPIO = 'FILTER_REPRESENTANTES_MUNICIPIO';
export const RESET_FILTER_REPRESENTANTES_MUNICIPIO = 'RESET_FILTER_REPRESENTANTES_MUNICIPIO';

export const FETCH_ALL_INSCRITOS_MUNICIPIO = 'FETCH_ALL_INSCRITOS_MUNICIPIO';
export const EMPTY_INSCRITOS_MUNICIPIO = 'EMPTY_INSCRITOS_MUNICIPIO';
export const FILTER_INSCRITOS_MUNICIPIO = 'FILTER_INSCRITOS_MUNICIPIO';
export const RESET_FILTER_INSCRITOS_MUNICIPIO = 'RESET_FILTER_INSCRITOS_MUNICIPIO';

export const FETCH_ALL_CLASSIFICADOS = 'FETCH_ALL_CLASSIFICADOS';
export const EMPTY_CLASSIFICADOS = 'EMPTY_CLASSIFICADOS';
export const FILTER_CLASSIFICADOS = 'FILTER_CLASSIFICADOS';
export const RESET_FILTER_CLASSIFICADOS = 'RESET_FILTER_CLASSIFICADOS';
